# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20181017_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
