# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_contact_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiXinImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('openid', models.CharField(max_length=100)),
                ('iamgeUrl', models.CharField(max_length=500)),
            ],
        ),
    ]
