# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20181017_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='imageArray',
            field=models.TextField(),
        ),
    ]
