# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20181017_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imageName', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/photos/image', verbose_name='\u6253\u5361\u7167\u7247')),
            ],
            options={
                'verbose_name_plural': '\u7167\u7247\u5217\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '\u5b66\u6821\u5217\u8868'},
        ),
    ]
